### ISSUE TITLE
No posts appear in homepage

### ISSUE THREAD

**Issue by donjar** [yous/whiteglass#5] opened 2017-03-30 09:54 UTC
Apparently no posts appear in my homepage. I need to add a `_layouts/home.html` page, changing line 12 from `{% for post in paginator.posts %}` to `{% for post in page.posts %}`.

Is this intentional? Do I need to install some paginator gem? I'm using Jekyll 3.4.3 with Whiteglass 1.3.0.

**Comment by yous** [comment] 2017-03-30 10:38
Hi, actually this theme uses jekyll-paginate gem, which is not [supported by GitHub Pages](https://help.github.com/articles/configuring-jekyll-plugins/). This is the reason of using [Travis CI](https://github.com/yous/whiteglass/blob/master/.travis.yml) to build the website. Maybe we can provide an option to select whether to use paginator or not, for compatibility with GitHub Pages.

**Comment by yous** [comment] 2017-03-30 10:41
If you still can't see the index page on your local machine, check out your `_config.yml`. There should be following lines:

``` yml
# Plugins
gems:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
```

**Comment by magic282** [comment] 2017-03-31 12:13
+1
Newbie here.
Also Jekyll 3.4.3 with Whiteglass 1.3.0.
Followed the official guide with fresh installation and replaced the theme and nothing showed up.

Even with 
```
# Plugins
gems:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
```

**Comment by yous** [comment] 2017-04-03 02:36
Hi @magic282, do the posts still not show up on your local machine? When it's the case, can you give me some example to reproduce the problem?

**Comment by magic282** [comment] 2017-04-03 07:53
Hi @yous I gave up setting it up. I just directly clone this repo and modify based on it, and it works now.

**Comment by yous** [comment] 2017-04-06 07:35
Hi, I just wrote up a [Quick Start instruction](https://github.com/yous/whiteglass/blob/master/README.md#quick-start), and I'm pretty sure that it will work. The reason that no posts in index page was that jekyll-paginate wasn't configured via `_config.yml`, and the file for the index page should be `index.html` instead of `index.md`.

Now I'm closing this. Feel free to open a new issue when there is a problem, and thank you for reporting!

**Closed by yous** 2017-04-06 07:35 UTC
